name: Docker build and publish
description: Kept for back-compat; use the more accurately named docker-build-publish workflow instead.

on:
  workflow_call:
    inputs:
      CSPROJ_NAME:
        type: string
        description: >
          The name of the .csproj file, expected to exist in an equally named folder in the root of the repository.
          Leave empty to skip dotnet build steps before building the image from the Dockerfile, e.g. for non-dotnet projects.
      DOTNET_VERSION:
        type: string
        default: "8"
        description: The version of the dotnet SDK, see https://github.com/actions/setup-dotnet/tree/v4/#supported-version-syntax.
      IMAGE_NAME:
        type: string
        required: true
        description: The full name of the image to be built and published, format should be registry/(owner)/image_name.
      majorMinorPatch:
        type: string
        required: true
        description: The major.minor.patch version. Use the git-version workflow template to generate this.
      preReleaseLabel:
        type: string
        required: true
        description: The pre-release label. Use the git-version workflow template to generate this.
      semVer:
        type: string
        required: true
        description: The semantic version. Use the git-version workflow template to generate this.
      assemblySemVer:
        type: string
        required: true
        description: The assembly semantic version. Use the git-version workflow template to generate this.
      assemblySemFileVer:
        type: string
        required: true
        description: The assembly semantic file version. Use the git-version workflow template to generate this.
      CR_REGISTRY:
        type: string
        default: docker.io
        description: The container registry to authenticate with.
    secrets:
      CR_USERNAME:
        required: true
        description: The username to authenticate with the container registry.
      CR_PASSWORD:
        required: true
        description: The password to authenticate with the container registry.

env:
  IS_MAIN: ${{ github.event.repository.default_branch == github.ref_name }}

jobs:
  build-publish:
    uses: bvandevliet/Actions.Shared/.github/workflows/docker-build-publish.yml@master
    with:
      CSPROJ_NAME: ${{ inputs.CSPROJ_NAME }}
      DOTNET_VERSION: ${{ inputs.DOTNET_VERSION }}
      IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
      majorMinorPatch: ${{ inputs.majorMinorPatch }}
      preReleaseLabel: ${{ inputs.preReleaseLabel }}
      semVer: ${{ inputs.semVer }}
      assemblySemVer: ${{ inputs.assemblySemVer }}
      assemblySemFileVer: ${{ inputs.assemblySemFileVer }}
      CR_REGISTRY: ${{ inputs.CR_REGISTRY }}
    secrets:
      CR_USERNAME: ${{ secrets.CR_USERNAME }}
      CR_PASSWORD: ${{ secrets.CR_PASSWORD }}
